// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthorized() {
  return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List booking leads/enquiries for the Human Size Ludo Experience, newest first. Optionally filter by status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by lead status, e.g. new, contacted, confirmed_booking."),
    limit: z.number().optional().describe("Max number of leads to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    let query = supabaseForUser(ctx).from("leads").select("*").order("created_at", { ascending: false }).limit(Math.min(limit ?? 25, 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { leads: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool2({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new booking enquiry (lead) for a Human Size Ludo event.",
  inputSchema: {
    name: z2.string().describe("Contact name."),
    phone: z2.string().describe("Contact phone number."),
    email: z2.string().describe("Contact email address."),
    city: z2.string().optional(),
    event_type: z2.string().optional().describe("e.g. Corporate Team Building, Wedding, Family Event."),
    event_date: z2.string().optional().describe("Event date in YYYY-MM-DD format."),
    participants: z2.number().optional(),
    message: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("leads").insert({ ...input, source: "mcp" }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data?.[0]) }], structuredContent: { lead: data?.[0] } };
  }
});

// src/lib/mcp/tools/update-lead-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var update_lead_status_default = defineTool3({
  name: "update_lead_status",
  title: "Update lead status",
  description: "Update the pipeline status of an existing lead (e.g. new, contacted, confirmed_booking, lost).",
  inputSchema: {
    lead_id: z3.string().describe("The lead's id."),
    status: z3.string().describe("New status value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("leads").update({ status }).eq("id", lead_id).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "No lead updated (not found or no access)." }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data[0]) }], structuredContent: { lead: data[0] } };
  }
});

// src/lib/mcp/tools/add-lead-note.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var add_lead_note_default = defineTool4({
  name: "add_lead_note",
  title: "Add lead note",
  description: "Attach a follow-up note to an existing lead.",
  inputSchema: {
    lead_id: z4.string().describe("The lead's id."),
    note: z4.string().describe("Note text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const { data, error } = await supabaseForUser(ctx).from("lead_notes").insert({ lead_id, note, created_by: ctx.getUserId() }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data?.[0]) }], structuredContent: { note: data?.[0] } };
  }
});

// src/lib/mcp/tools/list-follow-ups.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_follow_ups_default = defineTool5({
  name: "list_follow_ups",
  title: "List follow-up reminders",
  description: "List CRM follow-up reminders, soonest first. Optionally only pending (incomplete) ones.",
  inputSchema: {
    only_pending: z5.boolean().optional().describe("When true, exclude completed reminders."),
    limit: z5.number().optional().describe("Max reminders to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_pending, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    let query = supabaseForUser(ctx).from("follow_up_reminders").select("*").order("reminder_date", { ascending: true }).limit(Math.min(limit ?? 25, 100));
    if (only_pending) query = query.eq("completed", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { reminders: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iuduknnbzgdlfbocifwo";
var mcp_default = defineMcp({
  name: "human-size-ludo-mcp",
  title: "Human Size Ludo CRM",
  version: "0.1.0",
  instructions: "Tools for the Human Size Ludo Experience booking CRM. Use `list_leads` to review enquiries, `create_lead` to log a new booking enquiry, `update_lead_status` to move a lead through the pipeline, `add_lead_note` to record follow-up context, and `list_follow_ups` for upcoming reminders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, create_lead_default, update_lead_status_default, add_lead_note_default, list_follow_ups_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
